# Generated by Django 6.0.3 on 2026-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('boarding', 'Boarding'), ('sitting', 'House Sitting'), ('drop_in', 'Drop-in Visits'), ('daycare', 'Doggy Day Care'), ('walking', 'Dog Walking')], default='boarding', max_length=20),
            preserve_default=False,
        ),
    ]
