# Generated by Django 6.0.3 on 2026-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
