# Generated by Django 6.0.3 on 2026-04-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requester',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
